### ISSUE TITLE
[FEATURE] Want a page with normal headers that works both on mobile and desktop

### ISSUE THREAD

**Issue by saiftheboss7** [andersnoren/bjork#1]
I'm not really comfortable with a separate mobile menu and desktop menu. It'd be great if we can have an option for a single menu that works seamless on both mobile and desktop.

For example, [This is page on my website](https://saifhassan.info/about-me/). I want a normal header to apply on this page as well (Currently on desktop there's no top navigation - can't figure out how to do it!)

**Comment by andersnoren** [comment]
Hi @saiftheboss7,

First off, thanks for the creating the first issue in the repo!

The CSS that is hiding the header on desktop is targeting the `site-header` class, so you can set the header to be visible by removing that class from the header template part.

Go to Appearance → Editor, select the template that you want the header to remain visible on desktop on, select the header template part, expand the "Advanced" tab in the right sidebar, and remove the `site-header` class from field labeled "Additional CSS class(es)". That should take care of it.

I might add a "Header only" template in the future, but there's no easy way to make that a sitewide option for the theme.

— Anders

**Comment by saiftheboss7** [comment]
Thanks @andersnoren. I've figured this out!
