### ISSUE TITLE
line height with foot notes

### ISSUE THREAD

**Issue by icescalar** [andersnoren/bjork#13]
Dear Andres

First: Thanks for this incredibly beautiful theme! This is just a minor thing:

If i use footnotes in Texts, the line height somehow breaks. Every line with the footnote is a bit higher then the others. Would be nice to have a fix for that in a future version :)
<img width="461" alt="Bildschirmfoto 2024-06-30 um 12 28 46" src="https://github.com/andersnoren/bjork/assets/50198115/a1f6481e-abbe-4a46-81be-0b0247600381">

**Comment by andersnoren** [comment]
Hi @icescalar,

Thanks for the feedback and the kind words! I've improved the styling of the footnotes in 0.2.4, which should be available as an update now.

— Anders

**Comment by icescalar** [comment]
I can confirm that this is solved in 0.2.4, thanks!
