### ISSUE TITLE
Templates not accessible

### ISSUE THREAD

**Issue by Llcoolsouder** [andersnoren/bjork#6]
Hi,

I'm extremely new to Wordpress and I'm also not a web developer in general (like at all), so I'm sure this is a noob question.
I installed this theme for my Wordpress site, but when I create a new page I don't have access to your templates. For my home page (titled "Home"), the only templates available to me are "Default template," "Blank Canvas," and "No Title." What do I need to do to use your templates?

Thanks in advance!

**Comment by andersnoren** [comment]
@Llcoolsouder When you're running a block theme, like Björk, you can edit the templates in the Appearance → Editor page in the WordPress administration panel. In the Site Editor, you can switch between the different templates by clicking the WordPress logo in the top left and then the "Templates" menu item.

**Comment by Llcoolsouder** [comment]
Hey @andersnoren

Thanks for the help. Turns out, I just had  a fundamental misunderstanding about how templates worked in Wordpress. Things are moving along now!
